### PR TITLE
Updated index.php for new php-login setup

### PR DESCRIPTION
**Pull request by austinkregel**
Wanted to make sure your project wouldn't clash when a user updates their script, I recommend testing it to make sure this set up works. Mainly because I change the fundamentals about how the script accesses the configuration.

Best of luck.

### CODE REVIEW

**Comment by austinkregel** [comment]
I should note that this change in the bootstrap script has not been made, so a merge right now would actually break your project; however, changes will be made within the coming weeks, and I just wanted to give you a heads up about the change.

**Comment by Wargog** [comment]
Well, the index file uses custom views because it has to display stuff like the users repositories, the installer and other things, the files that need to be custom are the header, logged in page, and the footer, which are all set to use my custom views. I do see that the `req` method is no longer needed though, and could be removed.

**Comment by austinkregel** [comment]
The req method was actually messing up the rendering of the script and is no longer recommended. I found that out after messing with the script again.

**Comment by Wargog** [comment]
Done in next commit along with other series of changes, thank you though!

**Pull request closed without merging**
